# Generated by Django 4.2.5 on 2024-02-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="created", new_name="created_at",
        ),
        migrations.RemoveField(model_name="task", name="complete",),
        migrations.RemoveField(model_name="task", name="title",),
        migrations.AddField(
            model_name="task",
            name="user_input",
            field=models.CharField(default="", max_length=255),
        ),
    ]
