# Generated by Django 4.2.5 on 2024-02-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0002_rename_created_task_created_at_remove_task_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="user_input2",
            field=models.CharField(default="", max_length=255),
        ),
    ]
