# Generated by Django 4.2.5 on 2024-02-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0003_task_user_input2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="user_input", new_name="key_input",
        ),
        migrations.RenameField(
            model_name="task", old_name="user_input2", new_name="value_input",
        ),
    ]
